### PR TITLE
Allow baseUrl configuration to support enterprose versioneye api

### PR DESCRIPTION
**Pull request by kwiatekus**

### CODE REVIEW

**Comment by MaChristmann** [comment]
Hi kwiatekus
Thanks for improving this module for the usage of VersionEye Enterprise!
This makes sense and as we are using the Web-Version we did not thought about it yet.

Before I am gonna merge the pull request, I suggest to use baseUrl as a parameter for the constructor function, instead of using it as a parameter of the updateProject method. In future there might be more than just the updateProject method so I think it would be cleaner to use baseUrl als a part of the VersioneyeApi instance (similar like apiKey): 

``` javascript
function VersioneyeApi(baseUrl, apiKey) {
   this.baseUrl = baseUrl;
   this.apiKey = apiKey;
}
```

**Comment by reiz** [comment]
+1

**Comment by kwiatekus** [comment]
Hi guys!
Thanks for a quick response and review. I pushed the changes to initialize baseUrl via constructor.
Cheers

**Comment by MaChristmann** [comment]
Looks good! Thanks again

--> Merge

**Pull request merged**
